version: '3.8'

services:
  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      - CONFIG_PATH=/root/config
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=194393
      - POSTGRES_DB=go_services
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: